const {chromium} = require('playwright-core');
const {execFileSync} = require('child_process');
const path = require('path');
const assert = require('assert/strict');
(async () => {
 const browser = await chromium.launch({executablePath:process.env.CHROME_PATH || '/Applications/Google Chrome.app/Contents/MacOS/Google Chrome',headless:true});
 const page = await browser.newPage({viewport:{width:1000,height:700}});
 const errors=[]; page.on('pageerror', e=>{errors.push(e.message); console.log('ERROR',e.message)}); page.on('console', m=>{if(m.type()==='error') console.log(m.text())});
 await page.route('https://tunnel.evrim.zone/**', route => route.request().url().endsWith('/session') ? route.fulfill({json:{session_id:'solver-check'}}) : route.abort());
 await page.addInitScript(() => {
   localStorage.setItem('difficulty','Hard');
   window.jobs=[];
   window.Worker=class { constructor(){window.jobs.push(this)} postMessage(request){this.request=request} terminate(){this.terminated=true} };
 });
 await page.goto(process.env.DRAG_URL || 'http://127.0.0.1:8000/',{waitUntil:'domcontentloaded'});
 await page.waitForSelector('#game-canvas');
 const box=await page.locator('#game-canvas').boundingBox();
 const click=async(x,y)=>{ await page.mouse.click(box.x+(x+72)*box.width/400,box.y+(y+8)*box.height/272,{delay:100}); await page.waitForTimeout(350); };
 await page.waitForFunction(()=>window.jobs.length>0);
 assert.equal(await page.evaluate(()=>jobs[0].request.difficulty),'Easy');
 await click(248,210);
 assert.equal(await page.evaluate(()=>jobs[0].terminated),true);
 await click(26,178);
 assert.equal(await page.evaluate(()=>localStorage.getItem('difficulty')),'Easy');
 await click(72,178);
 assert.equal(await page.evaluate(()=>localStorage.getItem('difficulty')),'Normal');
 await click(120,178);
 assert.equal(await page.evaluate(()=>localStorage.getItem('difficulty')),'Hard');
 await click(128,248);
 await click(248,174);
 const count=await page.evaluate(()=>jobs.length);
 await click(96,112); await click(128,112);
 await page.waitForTimeout(500); await click(276,188); await click(276,188);
 await page.waitForFunction(n=>jobs.length>n,count);
 assert.equal(await page.evaluate(()=>jobs.at(-1).request.difficulty),'Easy');
 console.log('menu navigation cancellation, persisted selector, tutorial Easy override: passed');
 // Undo remains usable while thinking and disposes the pending job.
 await page.evaluate(()=>{window.obsolete=jobs.at(-1); window.late=obsolete.onmessage});
 await click(-16,145);
 assert.notEqual(await page.evaluate(()=>jobs.at(-1).terminated),true,'first undo click only arms confirmation');
 await click(-16,145);
 assert.equal(await page.evaluate(()=>jobs.at(-1).terminated),true);
 assert.deepEqual(errors,[]);
 await page.evaluate(()=>late({data:{...obsolete.request,selected:[[4,3],[4,2]]}}));
 await page.waitForTimeout(500);
 const nextCount=await page.evaluate(()=>jobs.length);
 await click(96,112); await click(128,112);
 await page.waitForFunction(n=>jobs.length>n,nextCount);
 assert.equal(await page.evaluate(()=>JSON.parse(jobs.at(-1).request.snapshot).turns.length),1);
 const rematchJob=await page.evaluate(()=>jobs.length-1);
 await click(-16,107); await click(128,116);
 assert.notEqual(await page.evaluate(i=>jobs[i].terminated,rematchJob),true,'first rematch click only arms confirmation');
 await click(128,116);
 assert.equal(await page.evaluate(i=>jobs[i].terminated,rematchJob),true);
 console.log('undo, late reply after undo, and rematch cancellation: passed');
 await browser.close();
})().catch(e=>{console.error(e);process.exit(1)});
